### ISSUE TITLE
Dual function keys, always hold on another key press

### ISSUE THREAD

**Issue by joakin** [Dygmalab/Bazecor#675]
**Is your feature request related to a problem? Please describe.**
I've encountered a problem with one of the thumb keys where I want the Escape function on tap and Ctrl on hold. When I type very quickly, rapid input of `Ctrl+<letter>` sometimes doesn't register as a hold, and I get an `Esc+<letter>` instead.

This issue is similar to one I experienced with a QMK keyboard, which I resolved by enabling [HOLD_ON_OTHER_KEY_PRESS](https://github.com/qmk/qmk_firmware/blob/master/docs/tap_hold.md#hold-on-other-key-press) in the configuration.

Essentially, I want the keyboard to treat any key press as a hold if another key is pressed simultaneously, without any timeouts or complications—if no other key is touched, it should register as a tap.

I've attempted to tweak the dual function key threshold settings and lowered the keys-overlap to 0 to ensure the hold function is recognized, but I continue to experience the same problem. I also tried reducing the Hold Timeout to 1, but then the tap function is never recognized, even when no other key is pressed, so `Esc` never fires. 

**Describe the solution you'd like**
I'd like to have a feature or setting implemented that handles rapid keypresses more accurately by always treating a key press as a hold when any other key is activated, similar to the `HOLD_ON_OTHER_KEY_PRESS` feature in QMK keyboards.

**Describe alternatives you've considered**
As mentioned, I've played around with the dual function key threshold and Hold Timeout settings, but neither has provided a satisfactory solution. I've had to stop using dual function keys and split the key into two places.

**Additional context**
The current behavior interrupts the flow of typing and could be a significant hindrance for fast typists using dual-function keys.

**Comment by Colburse** [comment]
This feature would be amazing. Dual function keys are unusable right now because of these nonsensical delays. This could all be solved by just doing what other programs (such as [keyd](https://github.com/rvaiya/keyd)) do.

**Comment by PapaNappa** [comment]
Occasionally, I fall for this behaviour as well.

For me, I have Ctrl/Backspace on a thumb key (I think this is the default for the Defy).
Sometimes, holding Ctrl and pressing another key, is registered as `<Backspace>, <key>`, instead of `<Ctrl>+<key>`.

However, what I observed, is that this only happens when you quickly let go of the other key first.

So, this works as expected, registering as `<Ctrl>+<s>`:
`<Ctrl/Bsp> down, <s> down, <s> up, <Ctrl/Bsp> up`

However, this is registered as `<Backspace>, <s>`, when typed quickly:
`<Ctrl/Bsp> down, <s> down, <Ctrl/Bsp> up, <s> up`

The question is: is this desired behaviour, or not?
Mostly, I would prefer having both sequences registed as `<Ctrl>+<s>`.

**Comment by MiquelDygma** [comment]
Hi!

I'm reviewing old issues and wanted to let you know that we added new settings for the dual-function keys that might help you get the behavior you want. 

You'll need the latest 2.0 firmware for the Dygma Defy. 

Let me know if that helps. 

Best,

**Comment by joakin** [comment]
I just updated the defy to 2.0.0 and bazecor to 1.7.0, and I still can't disable some of the timeouts:

![Image](https://github.com/user-attachments/assets/7f4d141a-b414-4e00-b720-5bf1c701f85a)

Only the overlap threshold can go to 0, Minimum Hold time smallest value is 1, and Hold timeout caps at 250 ms.

With those, pressing very quickly the dual fn key + another key yields the tap behavior, where it should hold. If you slow down a tiny bit then it triggers the hold fn. 

I configured the Shift / Space key to test with "Advanced modifiers": 

![Image](https://github.com/user-attachments/assets/70179a8e-ae95-456b-b026-b1808b8d451b)

Another issue is that the hold time caps at 255ms, so if you press the dual function key after 255ms if you let go it doesn't trigger the tap, even if it was only tapped by itself.


It would be great to have a way to say that if a key is tapped alone, it is a tap, if it overlaps with anything at all at any `time,` it is a hold. No other funky timeout business.

---

Anyway thank you for coming back to this Miquel, I understand it is not a priority since others don't care.

Let me know if I've missed any settings or done something wrong, or if there is any other place for the new settings for dual function keys.

**Comment by MiquelDygma** [comment]
Thank you for the detailed reply. 

Could you try lowering the Hold Timeout (the first setting) to something like 90ms? That should get you much closer to the behavior that you want.
